service: files-importer-api

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  apiGateway:
    apiKeys:
      - files-importer-api-key

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          private: true
          path: hello
          method: GET

plugins:
  - serverless-wsgi
  - serverless-python-requirements
