service: sls
frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  runtime: python3.11
  memorySize: 128
  region: us-east-1
  s3:
    slsETL:
      name: sls-etl

package:
  individually: true
  patterns:
      - '!**'

functions:
  thumbnail-generator:
    handler: handler.main
    package:
      patterns:
        - './handler.py'
    layers:
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p311-Pillow:2
    events:
      - s3:
          bucket: slsETL
          event: s3:ObjectCreated:*
          rules:
            - prefix: input/
